# Generated by Django 5.2.7 on 2026-05-18 20:25

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('title_es', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180)),
                ('description_es', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=bookings.models.additional_service_upload_to)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('allows_quantity', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('label_es', models.CharField(max_length=120)),
                ('label_en', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['sort_order', 'name_es'], 'verbose_name_plural': 'cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=40.4168, max_digits=9),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-3.7038, max_digits=9),
        ),
        migrations.AddField(
            model_name='city',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='bookings.amenity'),
        ),
    ]
