# Generated by Django 5.2.7 on 2026-05-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_additionalservice_amenity_alter_city_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_es', models.CharField(max_length=120, unique=True)),
                ('name_en', models.CharField(max_length=120, unique=True)),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('phone_code', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_es', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_es', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Wynwood House', max_length=120)),
                ('contact_email', models.EmailField(default='hello@wynwoodhouse.com', max_length=254)),
                ('contact_phone', models.CharField(default='+34 555 010 100', max_length=40)),
                ('promo_text_es', models.CharField(blank=True, max_length=180)),
                ('promo_text_en', models.CharField(blank=True, max_length=180)),
                ('promo_timer_label_es', models.CharField(blank=True, max_length=120)),
                ('promo_timer_label_en', models.CharField(blank=True, max_length=120)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('app_store_url', models.URLField(blank=True)),
                ('google_play_url', models.URLField(blank=True)),
                ('contact_cta_email', models.EmailField(default='hello@wynwoodhouse.com', max_length=254)),
                ('confirmation_tagline', models.CharField(default='Home Experience, Hotel Quality', max_length=180)),
                ('confirmation_social', models.CharField(default='@wynwood.house', max_length=120)),
                ('confirmation_policy_url', models.URLField(blank=True)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0.16, max_digits=5)),
                ('city_tax_rate', models.DecimalField(decimal_places=4, default=0.03, max_digits=5)),
                ('loyalty_discount', models.DecimalField(decimal_places=2, default=18.0, max_digits=10)),
                ('default_points_divisor', models.PositiveIntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_es', models.CharField(max_length=120)),
                ('label_en', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='bookings.footersection')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
